// Action Types //
// GENERAL APP
export const LOGIN_INFO = 'LOGIN_INFO';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_OKTA = 'LOGOUT_OKTA';
export const LOGOUT_MWB = 'LOGOUT_MWB';
export const APP_STOP_SHOWING_SERVER_MESSAGE = 'APP_STOP_SHOWING_SERVER_MESSAGE';
export const HEADER_SELECT_ICON = 'HEADER_SELECT_ICON';
export const CLIENT_CHANGE = 'CLIENT_CHANGE';
export const CLEAR_SELECTED_CLIENT = 'CLEAR_SELECTED_CLIENT';
export const SET_APP_HEADER_ACTION_ITEMS = 'SET_APP_HEADER_ACTION_ITEMS';
export const CHANGE_PRESENTATION_TYPE = 'CHANGE_PRESENTATION_TYPE';
export const VERSION_INFO = 'VERSION_INFO';
export const CONTEXT_MENU_CHANGE = 'CONTEXT_MENU_CHANGE';
export const MODAL_DIALOG_CHANGE = 'MODAL_DIALOG_CHANGE';
export const FILE_REMOVE_REQUEST = 'FILE_REMOVE_REQUEST';
export const FILE_REMOVE_ERROR = 'FILE_REMOVE_ERROR';
export const FILE_REMOVE_SUCCESS = 'FILE_REMOVE_SUCCESS';
export const APP_CONFIG_REQUEST = 'APP_CONFIG_REQUEST';
export const APP_CONFIG_SUCCESS = 'APP_CONFIG_SUCCESS';
export const APP_CONFIG_FAILURE = 'APP_CONFIG_FAILURE';
export const UPDATE_USER_GROUPS = 'UPDATE_USER_GROUPS';
// NOTIFICATIONS
export const BAD_REQUEST = 'BAD_REQUEST';
export const GOOD_REQUEST = 'GOOD_REQUEST';
export const WARNING_REQUEST = 'WARNING_REQUEST';
export const PERSISTENT_REQUEST = 'PERSISTENT_REQUEST';
// PROJECT
export const PROJECT_UPDATE = 'PROJECT_UPDATE';
export const PROJECT_STATUS_UPDATE = 'PROJECT_STATUS_UPDATE';
export const PROJECT_DEPLOYABLE_MODEL = 'PROJECT_DEPLOYABLE_MODEL';
export const PROJECT_OPEN = 'PROJECT_OPEN';
export const PROJECT_CLOSE = 'PROJECT_CLOSE';
export const PROJECT_DELETE = 'PROJECT_DELETE';
export const PROJECT_DATASET_ADD = 'PROJECT_DATASET_ADD';
export const SIDEBAR_SELECT_PROJECT = 'SIDEBAR_SELECT_PROJECT';
export const COLLAPSIBLE_SIDEBAR_SELECT = 'COLLAPSIBLE_SIDEBAR_SELECT';
// PROJECT TABLE
export const PROJECT_TABLE_CANCEL_RENDER = 'PROJECT_TABLE_CANCEL_RENDER';
// DATASET
export const DATASET_OPEN = 'DATASET_OPEN';
export const DATASET_CLOSE = 'DATASET_CLOSE';
export const DATASET_ADD_NAME = 'DATASET_ADD_NAME';
export const DATASET_ADD_DESCRIPTION = 'DATASET_ADD_DESCRIPTION';
export const DATASET_ADD_TYPE = 'DATASET_ADD_TYPE';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const PROJECT_LIST_LOADED_SUCCESS = 'PROJECT_LIST_LOADED_SUCCESS';
export const PROJECT_LIST_TOGGLE_VISIBLE = 'PROJECT_LIST_TOGGLE_VISIBLE';
export const DATASET_REMOVED_FROM_PROJECT = 'DATASET_REMOVED_FROM_PROJECT';
export const ADD_DATASET_TO_PROJECT_SUCCESS = 'ADD_DATASET_TO_PROJECT_SUCCESS'; // TODO: remove

export const RECEIVE_DATASET_FAIL = 'RECEIVE_DATASET_FAIL';
export const PROJECT_SHOW_ADD_GUIDE_DROPBOX = 'PROJECT_SHOW_ADD_GUIDE_DROPBOX';
// DATASET IMPORT TAGGING GUIDE
export const REQUEST_TAGGING_GUIDE = 'REQUEST_TAGGING_GUIDE';
export const RECEIVE_TAGGING_GUIDE_SUCCESS = 'RECEIVE_TAGGING_GUIDE_SUCCESS';
export const RECEIVE_TAGGING_GUIDE_FAIL = 'RECEIVE_TAGGING_GUIDE_FAIL';
// DATASET TRANSFORMED SEARCH
export const REQUEST_DATASET_SEARCH = 'REQUEST_DATASET_SEARCH';
export const RECEIVE_DATASET_SEARCH_SUCCESS = 'RECEIVE_DATASET_SEARCH_SUCCESS';
export const RECEIVE_DATASET_SEARCH_FAIL = 'RECEIVE_DATASET_SEARCH_FAIL';
export const REQUEST_DATASET_STATS = 'REQUEST_DATASET_STATS';
export const RECEIVE_DATASET_STATS_SUCCESS = 'RECEIVE_DATASET_STATS_SUCCESS';
export const RECEIVE_DATASET_STATS_FAIL = 'RECEIVE_DATASET_STATS_FAIL';
export const RECEIVE_DATASET_VALIDATION_STATS = 'RECEIVE_DATASET_VALIDATION_STATS';
export const DELETE_DATASET_VALIDATION_STATS = 'DELETE_DATASET_VALIDATION_STATS';
export const RESET_DATASET_VALIDATION_STATS = 'RESET_DATASET_VALIDATION_STATS';
export const DATASET_CHANGE_PAGE = 'DATASET_CHANGE_PAGE';
export const DATASET_CHANGE_LIMIT = 'DATASET_CHANGE_LIMIT';
// SERVER REQUEST / RECEIVE
export const REQUEST_PROJECTS_ALL = 'REQUEST_PROJECTS_ALL';
export const RECEIVE_PROJECTS_ALL = 'RECEIVE_PROJECTS_ALL';
export const REQUEST_PROJECTS_BY_CLIENT = 'REQUEST_PROJECTS_BY_CLIENT';
export const RECEIVE_PROJECTS_BY_CLIENT = 'RECEIVE_PROJECTS_BY_CLIENT';
export const REQUEST_PROJECT = 'REQUEST_PROJECT';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';
export const REQUEST_CLIENT_LIST = 'REQUEST_CLIENT_LIST';
export const RECEIVE_CLIENT_LIST = 'RECEIVE_CLIENT_LIST';
export const REQUEST_DATASET = 'REQUEST_DATASET';
export const RECEIVE_DATASET = 'RECEIVE_DATASET';
export const REQUEST_DATASET_LIST = 'REQUEST_DATASET_LIST';
export const RECEIVE_DATASET_LIST = 'RECEIVE_DATASET_LIST';
export const RESET_DATASET_TRANSFORM = 'RESET_DATASET_TRANSFORM';
export const REQUEST_DATASET_TRANSFORM = 'REQUEST_DATASET_TRANSFORM';
export const RECEIVE_DATASET_TRANSFORM_SUCCESS = 'RECEIVE_DATASET_TRANSFORM_SUCCESS';
export const RECEIVE_DATASET_TRANSFORM_PROGRESS = 'RECEIVE_DATASET_TRANSFORM_PROGRESS';
export const RECEIVE_DATASET_TRANSFORM_FAIL = 'RECEIVE_DATASET_TRANSFORM_FAIL';
export const REQUEST_DATASETS_BY_PROJECT_ID = 'REQUEST_DATASETS_BY_PROJECT_ID';
export const RECEIVE_DATASETS_BY_PROJECT_ID = 'RECEIVE_DATASETS_BY_PROJECT_ID';
export const INVALIDATE_PROJECT_LIST = 'INVALIDATE_PROJECT_LIST';
// export const REQUEST_DATASETS_TRANSFORMATION_STATUSES = "REQUEST_DATASETS_TRANSFORMATION_STATUSES";
// export const RECEIVE_DATASETS_TRANSFORMATION_STATUSES = "RECEIVE_DATASETS_TRANSFORMATION_STATUSES";
// SERVER REQUEST / TAG
export const REQUEST_TAG_MANUAL = 'REQUEST_TAG_MANUAL';
export const RECEIVE_TAG_MANUAL_SUCCESS = 'RECEIVE_TAG_MANUAL_SUCCESS';
export const RECEIVE_TAG_MANUAL_FAIL = 'RECEIVE_TAG_MANUAL_FAIL';
export const REQUEST_TAG_MANUAL_DELETE = 'REQUEST_TAG_MANUAL_DELETE';
export const RECEIVE_TAG_MANUAL_DELETE_SUCCESS = 'RECEIVE_TAG_MANUAL_DELETE_SUCCESS';
export const RECEIVE_TAG_MANUAL_DELETE_FAIL = 'RECEIVE_TAG_MANUAL_DELETE_FAIL';
export const REQUEST_TAG_SUGGEST = 'REQUEST_TAG_SUGGEST';
export const RECEIVE_TAG_SUGGEST_SUCCESS = 'RECEIVE_TAG_SUGGEST_SUCCESS';
export const RECEIVE_TAG_SUGGEST_FAIL = 'RECEIVE_TAG_SUGGEST_FAIL';
// SERVER REQUEST / TAG / BULK
export const REQUEST_BULK_TAG_MANUAL = 'REQUEST_BULK_TAG_MANUAL';
export const REQUEST_BULK_TAG_MANUAL_UPDATE = 'REQUEST_BULK_TAG_MANUAL_UPDATE';
export const REQUEST_BULK_TAG_MANUAL_MIXED = 'REQUEST_BULK_TAG_MANUAL_MIXED';
export const RECEIVE_BULK_TAG_MANUAL_SUCCESS = 'RECEIVE_BULK_TAG_MANUAL_SUCCESS';
export const RECEIVE_BULK_TAG_MANUAL_FAIL = 'RECEIVE_BULK_TAG_MANUAL_FAIL';
export const RECEIVE_BULK_TAG_MANUAL_UPDATE_SUCCESS = 'RECEIVE_BULK_TAG_MANUAL_UPDATE_SUCCESS';
export const RECEIVE_BULK_TAG_MANUAL_UPDATE_FAIL = 'RECEIVE_BULK_TAG_MANUAL_UPDATE_FAIL';
export const REQUEST_BULK_TAG_MANUAL_DELETE = 'REQUEST_BULK_TAG_MANUAL_DELETE';
export const RECEIVE_BULK_TAG_MANUAL_DELETE_SUCCESS = 'RECEIVE_BULK_TAG_MANUAL_DELETE_SUCCESS';
export const RECEIVE_BULK_TAG_MANUAL_DELETE_FAIL = 'RECEIVE_BULK_TAG_MANUAL_DELETE_FAIL';
export const BULK_TAG_INTENT_DELETED = 'BULK_TAG_INTENT_DELETED';
// TAGGING
export const CURSOR_UP = 'CURSOR_UP';
export const CURSOR_DOWN = 'CURSOR_DOWN';
export const CURSOR_LEFT = 'CURSOR_LEFT';
export const CURSOR_RIGHT = 'CURSOR_RIGHT';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_INTENT = 'UPDATE_INTENT';
export const UPDATE_CELL_ACTIVE = 'UPDATE_CELL_ACTIVE';
export const UPDATE_BULK_CELL_ACTIVE = 'UPDATE_BULK_CELL_ACTIVE';
export const SELECTED_TAG_SUGGEST = 'SELECTED_TAG_SUGGEST';
export const SELECTED_BULK_TAG = 'SELECTED_BULK_TAG';
export const UPDATE_WITH_TAG_SUGGEST = 'UPDATE_WITH_TAG_SUGGEST';
export const UPDATE_TAG_USER_ENTERED = 'UPDATE_TAG_USER_ENTERED';
export const UPDATE_BULK_TAG_USER_ENTERED = 'UPDATE_BULK_TAG_USER_ENTERED';
export const REMOVE_TAG_SUGGEST = 'REMOVE_TAG_SUGGEST';
export const FORGET_SELECTED_SUGGESTED_TAG = 'FORGET_SELECTED_SUGGESTED_TAG';
export const FORGET_SELECTED_SUGGESTED_BULK_TAG = 'FORGET_SELECTED_SUGGESTED_BULK_TAG';
export const UNCHECK_ALL_SELECTED_ROWS = 'UNCHECK_ALL_SELECTED_ROWS';
export const ALL_ROWS_UNCHECKED = 'ALL_ROWS_UNCHECKED';
export const SHOW_BULK_TAG_CELL = 'SHOW_BULK_TAG_CELL';
export const HIDE_BULK_TAG_CELL = 'HIDE_BULK_TAG_CELL';
export const COLUMN_SORT_CHANGE = 'COLUMN_SORT_CHANGE';
// TAGGING CELL STATE / COMMON
export const CELL_ACTIVITY_FOCUSSED = 'CELL_ACTIVITY_FOCUSSED';
export const CELL_ACTIVITY_NONE = 'CELL_ACTIVITY_NONE';
// TAGGING CELL STATE / INTENT
export const CELL_ACTIVITY_TYPING_INTENT = 'CELL_ACTIVITY_TYPING_INTENT';
export const CELL_ACTIVITY_BACKSPACING_INTENT = 'CELL_ACTIVITY_BACKSPACING_INTENT';
export const CELL_ACTIVITY_SUGGESTED_TAG_SELECTED = 'CELL_ACTIVITY_SUGGESTED_TAG_SELECTED'; // selected
export const CELL_ACTIVITY_SUGGESTED_TAG_UPDATED = 'CELL_ACTIVITY_SUGGESTED_TAG_UPDATED'; // updated but not selected
export const CELL_INTENT_STATUS_ADDED = 'CELL_INTENT_STATUS_ADDED';
export const CELL_INTENT_STATUS_REMOVED = 'CELL_INTENT_STATUS_REMOVED';
export const CELL_INTENT_STATUS_NONE = 'CELL_INTENT_STATUS_NONE';
// TAGGING CELL STATE / BULK
export const CELL_TYPE_MANUAL = 'CELL_TYPE_MANUAL';
export const CELL_TYPE_MANUAL_BULK = 'CELL_TYPE_MANUAL_BULK';
// TAGGING CELL STATE / COMMENTS
export const CELL_TYPE_COMMENTS = 'CELL_TYPE_COMMENTS';
export const CELL_ACTIVITY_TYPING_COMMENTS = 'CELL_ACTIVITY_TYPING_COMMENTS';
export const CELL_ACTIVITY_BACKSPACING_COMMENTS = 'CELL_ACTIVITY_BACKSPACING_COMMENTS';
export const CELL_COMMENTS_STATUS_ADDED = 'CELL_COMMENTS_STATUS_ADDED';
export const CELL_COMMENTS_STATUS_REMOVED = 'CELL_COMMENTS_STATUS_REMOVED';
export const CELL_COMMENTST_STATUS_NONE = 'CELL_COMMENTST_STATUS_NONE';
// TABLE
export const SORTED_ASCENDING = 'asc';
export const SORTED_DESCENDING = 'desc';
export const SORTED_NONE = 'SORTED_NONE';
export const TABLE_SEARCH_RESULTS_UPDATE = 'TABLE_SEARCH_RESULTS_UPDATE';
// TAGGING GUIDE
export const TAGGING_GUIDE_REQUEST_PROJECT = 'TAGGING_GUIDE_REQUEST_PROJECT';
export const TAGGING_GUIDE_RECEIVE_PROJECT = 'TAGGING_GUIDE_RECEIVE_PROJECT';
export const TAGGING_GUIDE_REQUEST_SEARCH = 'TAGGING_GUIDE_REQUEST_SEARCH';
export const TAGGING_GUIDE_RECEIVE_SEARCH = 'TAGGING_GUIDE_RECEIVE_SEARCH';
export const TAGGING_GUIDE_REQUEST_TAG_REMOVE = 'TAGGING_GUIDE_REQUEST_TAG_REMOVE';
export const TAGGING_GUIDE_RECEIVE_TAG_REMOVE = 'TAGGING_GUIDE_RECEIVE_TAG_REMOVE';
export const TAGGING_GUIDE_REQUEST_TAG_UPDATE = 'TAGGING_GUIDE_REQUEST_TAG_UPDATE';
export const TAGGING_GUIDE_RECEIVE_TAG_UPDATE = 'TAGGING_GUIDE_RECEIVE_TAG_UPDATE';
export const TAGGING_GUIDE_REQUEST_TAG_CREATE = 'TAGGING_GUIDE_REQUEST_TAG_CREATE';
export const TAGGING_GUIDE_RECEIVE_TAG_CREATE = 'TAGGING_GUIDE_RECEIVE_TAG_CREATE';
export const TAGGING_GUIDE_RESET = 'TAGGING_GUIDE_RESET';
export const TAGGING_GUIDE_REQUEST_LAST_IMPORT_INFO = 'TAGGING_GUIDE_REQUEST_LAST_IMPORT_INFO';
export const TAGGING_GUIDE_RECEIVE_LAST_IMPORT_INFO = 'TAGGING_GUIDE_RECEIVE_LAST_IMPORT_INFO';
// PROJECTS MANAGER
export const PROJECTS_MANAGER_PROJECT_LOAD_REQUEST = 'PROJECTS_MANAGER_PROJECT_LOAD_REQUEST';
export const PROJECTS_MANAGER_PROJECT_LOAD_ERROR = 'PROJECTS_MANAGER_PROJECT_LOAD_ERROR';
export const PROJECTS_MANAGER_PROJECT_LOAD_SUCCESS = 'PROJECTS_MANAGER_PROJECT_LOAD_SUCCESS';
export const PROJECTS_MANAGER_PROJECT_DATASETS_LOAD_REQUEST = 'PROJECTS_MANAGER_PROJECT_DATASETS_LOAD_REQUEST';
export const PROJECTS_MANAGER_PROJECT_DATASETS_LOAD_ERROR = 'PROJECTS_MANAGER_PROJECT_DATASETS_LOAD_ERROR';
export const PROJECTS_MANAGER_PROJECT_DATASETS_LOAD_SUCCESS = 'PROJECTS_MANAGER_PROJECT_DATASETS_LOAD_SUCCESS';
export const PROJECTS_MANAGER_PROJECT_INTENTS_LOAD_REQUEST = 'PROJECTS_MANAGER_PROJECT_INTENTS_LOAD_REQUEST';
export const PROJECTS_MANAGER_PROJECT_INTENTS_LOAD_ERROR = 'PROJECTS_MANAGER_PROJECT_INTENTS_LOAD_ERROR';
export const PROJECTS_MANAGER_PROJECT_INTENTS_LOAD_SUCCESS = 'PROJECTS_MANAGER_PROJECT_INTENTS_LOAD_SUCCESS';
export const PROJECTS_MANAGER_PROJECT_CONFIGS_LOAD_REQUEST = 'PROJECTS_MANAGER_PROJECT_CONFIGS_LOAD_REQUEST';
export const PROJECTS_MANAGER_PROJECT_CONFIGS_LOAD_ERROR = 'PROJECTS_MANAGER_PROJECT_CONFIGS_LOAD_ERROR';
export const PROJECTS_MANAGER_PROJECT_CONFIGS_LOAD_SUCCESS = 'PROJECTS_MANAGER_PROJECT_CONFIGS_LOAD_SUCCESS';
export const PROJECTS_MANAGER_DATASETS_STATUSES_LOAD_REQUEST = 'PROJECTS_MANAGER_DATASETS_STATUSES_LOAD_REQUEST';
export const PROJECTS_MANAGER_DATASETS_STATUSES_LOAD_ERROR = 'PROJECTS_MANAGER_DATASETS_STATUSES_LOAD_ERROR';
export const PROJECTS_MANAGER_DATASETS_STATUSES_LOAD_SUCCESS = 'PROJECTS_MANAGER_DATASETS_STATUSES_LOAD_SUCCESS';
export const PROJECTS_MANAGER_PROJECT_UPDATED = 'PROJECTS_MANAGER_PROJECT_UPDATED';
export const PROJECTS_MANAGER_DATASET_UPDATED = 'PROJECTS_MANAGER_DATASET_UPDATED';
export const PROJECTS_MANAGER_PROJECT_MODELS_LOAD_REQUEST = 'PROJECTS_MANAGER_PROJECT_MODELS_LOAD_REQUEST';
export const PROJECTS_MANAGER_PROJECT_MODELS_LOAD_SUCCESS = 'PROJECTS_MANAGER_PROJECT_MODELS_LOAD_SUCCESS';
export const PROJECTS_MANAGER_PROJECT_MODELS_LOAD_ERROR = 'PROJECTS_MANAGER_PROJECT_MODELS_LOAD_ERROR';
export const PROJECTS_MANAGER_MODEL_UPDATED = 'PROJECTS_MANAGER_MODEL_UPDATED';
// TAGGING GUIDE IMPORT
export const TAGGING_GUIDE_IMPORT_RESET = 'TAGGING_GUIDE_IMPORT_RESET';
export const TAGGING_GUIDE_IMPORT_FILE_UPLOAD_SUCCESS = 'TAGGING_GUIDE_IMPORT_FILE_UPLOAD_SUCCESS';
export const TAGGING_GUIDE_IMPORT_ABORT_REQUEST = 'TAGGING_GUIDE_IMPORT_ABORT_REQUEST';
export const TAGGING_GUIDE_IMPORT_ABORT_ERROR = 'TAGGING_GUIDE_IMPORT_ABORT_ERROR';
export const TAGGING_GUIDE_IMPORT_ABORT_SUCCESS = 'TAGGING_GUIDE_IMPORT_ABORT_SUCCESS';
export const TAGGING_GUIDE_IMPORT_COMMIT_REQUEST = 'TAGGING_GUIDE_IMPORT_COMMIT_REQUEST';
export const TAGGING_GUIDE_IMPORT_COMMIT_ERROR = 'TAGGING_GUIDE_IMPORT_COMMIT_ERROR';
export const TAGGING_GUIDE_IMPORT_COMMIT_SUCCESS = 'TAGGING_GUIDE_IMPORT_COMMIT_SUCCESS';
export const TAGGING_GUIDE_IMPORT_COLUMNS_BIND = 'TAGGING_GUIDE_IMPORT_COLUMNS_BIND';
export const TAGGING_GUIDE_IMPORT_FISRT_ROW_SKIP_CHANGE = 'TAGGING_GUIDE_IMPORT_FISRT_ROW_SKIP_CHANGE';
export const TAGGING_GUIDE_IMPORT_COLUMNS_BIND_REQUEST = 'TAGGING_GUIDE_IMPORT_COLUMNS_BIND_REQUEST';
export const TAGGING_GUIDE_IMPORT_COLUMNS_BIND_ERROR = 'TAGGING_GUIDE_IMPORT_COLUMNS_BIND_ERROR';
export const TAGGING_GUIDE_IMPORT_COLUMNS_BIND_SUCCESS = 'TAGGING_GUIDE_IMPORT_COLUMNS_BIND_SUCCESS';
export const TAGGING_GUIDE_IMPORT_CHANGE_STEP = 'TAGGING_GUIDE_IMPORT_CHANGE_STEP';
// TAG DATASETS
export const TAG_DATASETS_CLEANUP = 'TAG_DATASETS_CLEANUP';
export const TAG_DATASETS_SET_PROJECT_ID = 'TAG_DATASETS_SET_PROJECT_ID';
export const TAG_DATASETS_SET_PROJECT = 'TAG_DATASETS_SET_PROJECT';
export const TAG_DATASETS_SET_DATASETS = 'TAG_DATASETS_SET_DATASETS';
export const TAG_DATASETS_SET_DATASETS_FILTER = 'TAG_DATASETS_SET_DATASETS_FILTER';
export const TAG_DATASETS_SET_INCOMING_FILTER = 'TAG_DATASETS_SET_INCOMING_FILTER';
export const TAG_DATASETS_SET_FOCUS = 'TAG_DATASETS_SET_FOCUS';
export const TAG_DATASETS_SET_CONTROLS_COLLAPSE = 'TAG_DATASETS_SET_CONTROLS_COLLAPSE';
// CONSISTENCY REPORT
export const CONSISTENCY_REPORT_RESET = 'CONSISTENCY_REPORT_RESET';
export const CONSISTENCY_REPORT_SET_PROJECT_ID = 'CONSISTENCY_REPORT_SET_PROJECT_ID';
export const CONSISTENCY_REPORT_SET_PROJECT = 'CONSISTENCY_REPORT_SET_PROJECT';
export const CONSISTENCY_REPORT_SET_DATASETS = 'CONSISTENCY_REPORT_SET_DATASETS';
export const CONSISTENCY_REPORT_SET_FILTER = 'CONSISTENCY_REPORT_SET_FILTER';
export const CONSISTENCY_REPORT_REQUEST_SEARCH_REQUEST = 'CONSISTENCY_REPORT_REQUEST_SEARCH_REQUEST';
export const CONSISTENCY_REPORT_REQUEST_SEARCH_ERROR = 'CONSISTENCY_REPORT_REQUEST_SEARCH_ERROR';
export const CONSISTENCY_REPORT_REQUEST_SEARCH_SUCCESS = 'CONSISTENCY_REPORT_REQUEST_SEARCH_SUCCESS';
export const CONSISTENCY_REPORT_SET_PAGER_SETTINGS = 'CONSISTENCY_REPORT_SET_PAGER_SETTINGS';
export const CONSISTENCY_REPORT_REFRESH = 'CONSISTENCY_REPORT_REFRESH';
// MODELS
export const MODEL_CREATED = 'MODEL_CREATED';
export const NEW_MODEL = 'NEW_MODEL';
export const MODEL_EDIT_UPDATE = 'MODEL_EDIT_UPDATE';
export const RECIEVE_MODEL_TEST_RESULTS = 'RECIEVE_MODEL_TEST_RESULTS';
export const CLEAR_MODEL_TEST_RESULTS = 'CLEAR_MODEL_TEST_RESULTS';
export const MODEL_BATCH_TEST_RESULTS = 'MODEL_BATCH_TEST_RESULTS';
export const CLEAR_MODEL_BATCH_TEST_RESULTS = 'CLEAR_MODEL_BATCH_TEST_RESULTS';
export const MODEL_BATCH_JOB_REQUEST = 'MODEL_BATCH_JOB_REQUEST';
export const LIST_BATCH_TESTS_INFO = 'LIST_BATCH_TESTS_INFO';
export const CLEAR_LIST_BATCH_TESTS_INFO = 'CLEAR_LIST_BATCH_TESTS_INFO';
export const CLEAR_MODEL_DATA = 'CLEAR_MODEL_DATA';
export const TUNE_MODEL_ID = 'TUNE_MODEL_ID';
export const VIEW_MODEL_ID = 'VIEW_MODEL_ID';
export const MODEL_UPDATE = 'MODEL_UPDATE';
export const CLEAR_VIEW_MODEL_VIEW = 'CLEAR_VIEW_MODEL_VIEW';
export const SHOW_MODEL_NAVIGATION_CONFIRMATION_DIALOG = 'SHOW_MODEL_NAVIGATION_CONFIRMATION_DIALOG';
export const CHECK_MODEL_TEST_RESULTS_FAILED = 'CHECK_MODEL_TEST_RESULTS_FAILED';
export const MODEL_DELETED_FROM_PROJECT = 'MODEL_DELETED_FROM_PROJECT';
export const MODEL_DELETE_FAILED = 'MODEL_DELETE_FAILED';
export const MODEL_ALREADY_DELETED = 'MODEL_ALREADY_DELETED';
export const INITIATE_UTTERANCE_TEST = 'INITIATE_UTTERANCE_TEST';
export const BEGIN_MODEL_TEST_AUDIO_UPLOAD = 'BEGIN_MODEL_TEST_AUDIO_UPLOAD';
export const MODEL_TEST_AUDIO_UPLOAD_FAIL = 'MODEL_TEST_AUDIO_UPLOAD_FAIL';
export const MODEL_TEST_AUDIO_UPLOAD_SUCCESS = 'MODEL_TEST_AUDIO_UPLOAD_SUCCESS';
export const UPDATE_SPEECH_MODEL_ID_FOR_DIGITAL_MODEL = 'UPDATE_SPEECH_MODEL_ID_FOR_DIGITAL_MODEL';
export const RECEIVE_PROJECT_PREFERENCE = 'RECEIVE_PROJECT_PREFERENCE';
export const RECEIVE_LATEST_TECHNOLOGY = 'RECEIVE_LATEST_TECHNOLOGY';

// CONFIGS
export const CONFIG_UPLOAD = 'CONFIG_UPLOAD';
export const CONFIG_UPLOAD_SUCCESS = 'CONFIG_UPLOAD_SUCCESS';
export const CONFIG_UPLOAD_FAIL = 'CONFIG_UPLOAD_FAIL';
export const CONFIG_CREATED = 'CONFIG_CREATED';
export const CONFIG_UPDATED = 'CONFIG_UPDATED';
export const REQUEST_CONFIG = 'REQUEST_CONFIG';
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';
export const CONFIG_EDIT_UPDATE = 'CONFIG_EDIT_UPDATE';
export const CONVERT_TO_SPEECH_CONFIG = 'CONVERT_TO_SPEECH_CONFIG';
export const CONVERT_TO_DIGITAL_CONFIG = 'CONVERT_TO_DIGITAL_CONFIG';
export const CONFIG_SHOW_TRANSFORMATION_DELETE_DIALOG = 'CONFIG_SHOW_TRANSFORMATION_DELETE_DIALOG';
export const UPDATE_TRAINING_CONFIG_VALIDITY = 'UPDATE_TRAINING_CONFIG_VALIDITY';
export const UPDATE_TRANSFORMATION_VALIDITY = 'UPDATE_TRANSFORMATION_VALIDITY';
export const CONFIG_SHOW_TRANSFORMATION_ADD_DIALOG = 'CONFIG_SHOW_TRANSFORMATION_ADD_DIALOG';
export const CONFIG_SHOW_TRANSFORMATION_PREDEFINED_DIALOG = 'CONFIG_SHOW_TRANSFORMATION_PREDEFINED_DIALOG';
// CREATE DATASET DIALOG
export const CREATE_DATASET_DIALOG_ABORT_REQUEST = 'CREATE_DATASET_DIALOG_ABORT_REQUEST';
export const CREATE_DATASET_DIALOG_ABORT_ERROR = 'CREATE_DATASET_DIALOG_ABORT_ERROR';
export const CREATE_DATASET_DIALOG_ABORT_SUCCESS = 'CREATE_DATASET_DIALOG_ABORT_SUCCESS';
export const CREATE_DATASET_DIALOG_RESET = 'CREATE_DATASET_DIALOG_RESET';
export const CREATE_DATASET_DIALOG_FILE_UPLOAD_SUCCESS = 'CREATE_DATASET_DIALOG_FILE_UPLOAD_SUCCESS';
export const CREATE_DATASET_DIALOG_CHANGE_STEP = 'CREATE_DATASET_DIALOG_CHANGE_STEP';
export const CREATE_DATASET_DIALOG_COLUMNS_BIND = 'CREATE_DATASET_DIALOG_COLUMNS_BIND';
export const CREATE_DATASET_DIALOG_FISRT_ROW_SKIP_CHANGE = 'CREATE_DATASET_DIALOG_FISRT_ROW_SKIP_CHANGE';
export const CREATE_DATASET_DIALOG_COLUMNS_BIND_REQUEST = 'CREATE_DATASET_DIALOG_COLUMNS_BIND_REQUEST';
export const CREATE_DATASET_DIALOG_COLUMNS_BIND_ERROR = 'CREATE_DATASET_DIALOG_COLUMNS_BIND_ERROR';
export const CREATE_DATASET_DIALOG_COLUMNS_BIND_SUCCESS = 'CREATE_DATASET_DIALOG_COLUMNS_BIND_SUCCESS';
export const CREATE_DATASET_DIALOG_AUTO_TAG_CHANGE = 'CREATE_DATASET_DIALOG_AUTO_TAG_CHANGE';
export const CREATE_DATASET_DIALOG_START_TRANSFORM_CHANGE = 'CREATE_DATASET_DIALOG_START_TRANSFORM_CHANGE';
export const CREATE_DATASET_REQUEST = 'CREATE_DATASET_REQUEST';
export const CREATE_DATASET_ERROR = 'CREATE_DATASET_ERROR';
export const CREATE_DATASET_SUCCESS = 'CREATE_DATASET_SUCCESS';
// CELL EDITABLE
export const CELL_EDITABLE_STATE_CREATE = 'CELL_EDITABLE_STATE_CREATE';
export const CELL_EDITABLE_STATE_RESET = 'CELL_EDITABLE_STATE_RESET';
export const CELL_EDITABLE_STATE_REMOVE = 'CELL_EDITABLE_STATE_REMOVE';
export const CELL_EDITABLE_SET_ACTIVE_CELL = 'CELL_EDITABLE_SET_ACTIVE_CELL';
export const CELL_EDITABLE_UPDATE_VALUE = 'CELL_EDITABLE_UPDATE_VALUE';
// CELL EDITABLE MANUAL TAG SUGGEST
export const CELL_EDITABLE_MANUAL_TAG_SUGGEST_STATE_CREATE = 'CELL_EDITABLE_MANUAL_TAG_SUGGEST_STATE_CREATE';
export const CELL_EDITABLE_MANUAL_TAG_SUGGEST_STATE_RESET = 'CELL_EDITABLE_MANUAL_TAG_SUGGEST_STATE_RESET';
export const CELL_EDITABLE_MANUAL_TAG_SUGGEST_STATE_REMOVE = 'CELL_EDITABLE_MANUAL_TAG_SUGGEST_STATE_REMOVE';
export const GET_SUGGESTED_TAGS_REQUEST = 'GET_SUGGESTED_TAGS_REQUEST';
export const GET_SUGGESTED_TAGS_ERROR = 'GET_SUGGESTED_TAGS_ERROR';
export const GET_SUGGESTED_TAGS_SUCCESS = 'GET_SUGGESTED_TAGS_SUCCESS';
export const CELL_SUGGEST_CURSOR_DOWN = 'CELL_SUGGEST_CURSOR_DOWN';
export const CELL_SUGGEST_CURSOR_UP = 'CELL_SUGGEST_CURSOR_UP';
// TAGS
export const SET_TAG_REQUEST = 'SET_TAG_REQUEST';
export const SET_TAG_ERROR = 'SET_TAG_ERROR';
export const SET_TAG_SUCCESS = 'SET_TAG_SUCCESS';
export const REMOVE_TAG_REQUEST = 'REMOVE_TAG_REQUEST';
export const REMOVE_TAG_ERROR = 'REMOVE_TAG_ERROR';
export const REMOVE_TAG_SUCCESS = 'REMOVE_TAG_SUCCESS';
export const SET_COMMENT_REQUEST = 'SET_COMMENT_REQUEST';
export const SET_COMMENT_ERROR = 'SET_COMMENT_ERROR';
export const SET_COMMENT_SUCCESS = 'SET_COMMENT_SUCCESS';
export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
// REPORTS
export const REPORTS_RESET = 'REPORTS_RESET';
export const REPORTS_SET_PROJECT_ID = 'REPORTS_SET_PROJECT_ID';
export const REPORTS_SET_INCOMING_FILTER = 'REPORTS_SET_INCOMING_FILTER';
export const REPORTS_SET_FILTER = 'REPORTS_SET_FILTER';
export const REPORTS_GET_REPORT_TYPES_REQUEST = 'REPORTS_GET_REPORT_TYPES_REQUEST';
export const REPORTS_GET_REPORT_TYPES_ERROR = 'REPORTS_GET_REPORT_TYPES_ERROR';
export const REPORTS_GET_REPORT_TYPES_SUCCESS = 'REPORTS_GET_REPORT_TYPES_SUCCESS';
// Action for testing
export const NOOP = 'NOOP';
// SETTINGS
export const DEFAULT_TECHNOLOGY = 'DEFAULT_TECHNOLOGY';
export const VECTORIZER = 'VECTORIZER';
