
module.exports = {
  featureFlags: {
    MWB_ROLE_EXTERNAL: {
      modelTrainingOutputs: 'hide',
      modelDownload: 'hide',
      kibanaLogs: 'hide',
      appHelp: 'hide',
      transformationHelp: 'hide',
      tagSearchHelp: 'hide',
      modelConfigDownload: 'hide',
      modelStatistics: 'hide',
      modelDelete: 'hide',
      modelConfigTemplate: 'hide',
      datasetTemplate: 'hide',
      intentGuideTemplate: 'hide',
      datasetExport: 'hide',
      datasetDelete: 'hide',
      intentGuideExport: 'hide',
      datasetExportById: 'hide',
      projectDelete: 'hide',
      downloadResults: 'hide',
      createNewVersionTrainingConfigTab: 'hide',
      createNewVersionModelReviewTab: 'hide',
      granularMessage: 'hide',
      intentGuideDelete: 'hide',
      intentGuideUpdate: 'hide',
      resolveInconsistencies: 'hide',
      intentGuideContextualActionBar: 'hide',
      speechBundledUnbundled: 'hide',
      datasetType: 'hide',
      suggestedIntent: 'hide',
      supportLink: 'hide',
    },
    DEFAULT: {
      models: 'show',
      modelTrainingOutputs: 'show',
      modelDownload: 'show',
      kibanaLogs: 'show',
      appHelp: 'show',
      transformationHelp: 'show',
      tagSearchHelp: 'show',
      modelConfigDownload: 'show',
      modelStatistics: 'show',
      modelDelete: 'show',
      modelConfigTemplate: 'show',
      datasetTemplate: 'show',
      intentGuideTemplate: 'show',
      datasetExport: 'show',
      datasetDelete: 'show',
      intentGuideExport: 'show',
      datasetExportById: 'show',
      projectDelete: 'show',
      downloadResults: 'show',
      createNewVersionTrainingConfigTab: 'show',
      createNewVersionModelReviewTab: 'show',
      granularMessage: 'show',
      intentGuideDelete: 'show',
      intentGuideUpdate: 'show',
      intentGuideContextualActionBar: 'show',
      resolveInconsistencies: 'show',
      speechBundledUnbundled: 'show',
      datasetType: 'show',
      suggestedIntent: 'show',
      supportLink: 'show',
    },
  },
};
