const synonymsSet3 = () => {
  const regex = {
    type: 'regex-replace',
    mappings: {
      '/\\b(gen\\S* equiv\\S* dipl\\S*|general\\S* edu\\S* degree\\S*|GED\\S*|general\\S* edu\\S* dev\\S*|HSED\\S*|.?SED|GDE|( ( highschool\\S*|high.?school\\S*|gen.?r.?l\\S* ) && (edu\\S*|equiv\\S* ) && (degree\\S*|diploma\\S*|dev\\S* ) ))\\b/i': 'GeneralEduDiploma',
      '/\\b(grade\\S*|grading\\S*|mark|marks\\S*|marking\\S*|score\\S*|result\\S*)\\b/i': 'Grade',
      '/\\b(graduation\\S*|graduate|graduates|conv.?cat\\S*|commenc\\S*|comenc\\S*|((grad\\S*|conv.?cat\\S*|commenc\\S*|comenc\\S*) && (cer.?mon\\S*|celebrat\\S*|event\\S*)))\\b/i': 'Graduation',
      '/\\b(health care provider\\S*|hcp|health provider\\S*|healthcare provider\\S*|provider\\S*)\\b/i': 'HealthCareProvider',
      '/\\b((health\\S* && ( clin\\S*|cent\\S*|building\\S* ) )|hospi\\S*|clinic\\S*)\\b/i': 'HealthClinic',
      '/\\b(help\\S*|assist\\S*|aid\\S*|support\\S*|suport\\S*|guid\\S*|how.?to|walk.?through\\S*|walkthrough\\S*|walk\\S* through|advice\\S*|troubleshoot\\S*|trouble.?shoot\\S* )\\b/i': 'Help',
      '/\\b(highschool\\S*|high.?school\\S*|high school\\S*|second.?r\\S* school\\S*|( grade\\S* && (twel\\S*|eleven\\S*|ten\\S*|nin\\S* ) ))\\b/i': 'HighSchool',
      '/\\b(fast|faster|quick|speed\\S*|rapid\\S*|brisk\\S*|hast\\S*|swift\\S*|accelerat\\S*|soon|expedit\\S*)\\b/i': 'Fast',
      '/\\b(evening\\S*|night\\S*|nite\\S*|dusk\\S*|midnight \\S*|bed.?time|bedtime|dark)\\b/i': 'Evening',
      '/\\b(assignment\\S*|homework\\S*|home.?work\\S*|project|projects|take.?home work\\S*)\\b/i': 'Homework',
      '/\\b(identi\\S*|idente\\S*|identa\\S*|ID|I.?D.?|I.?D )\\b/i': 'Identity ',
      '/\\b(internation\\S*|foreign\\S*|for.?.?gn\\S*|another countr\\S*|diff\\S* countr\\S*|other countr\\S*|oversea\\S*|abroad|world\\S*|glob\\S*)\\b/i': 'International',
      '/\\b(interview\\S*|try\\S* out|tryout\\S*|try.?out\\S*|walk\\S* on\\S*|walkon\\S*|walk.?on\\S*|audition\\S*)\\b/i': 'Interview',
      '/\\b(invest\\S* )\\b/i': 'Investment',
      '/\\b(((did not|didn.?t\\S*|do\\S* not|don.?t\\S*|does not\\S*|doesn.?t\\S* ) && have)|((is not|isn.?t\\S*|are not|aren.?t\\S*|arne.?t\\S*|arn.?t\\S*) && there)|has not|hasn.?t\\S*|have not|haven.?t\\S*|lack\\S*|without|nonexist\\S*|non.?exist\\S*|short.?of)\\b/i': 'Lacking',
      '/\\b(late|tardy|belate\\S*|behind\\S*|lag|lags|lagging|overdue\\S*|over.?due\\S*|held.?up )\\b/i': 'Late',
      '/\\b(month\\S*|january\\S*|jan|jan.?|february\\S*|febuary\\S*|feb|feb.?|march\\S*|mar|april\\S*|apr|apr.?|may|may.?|may.?s|june\\S*|jun|jun.?|july\\S*|jul|jul.?|august|aug|aug.?|september\\S*|sep|sept|sep.?|sept.?|october\\S*|oct|oct.?|november\\S*|nov|nov.?|december\\S*|dec|dec.? )\\b/i': 'Months',
      '/\\b(leave\\S*|leaving\\S*|left\\S*|abandon\\S*|desert\\S*|ditch\\S*|quit\\S*|resign\\S*|exit\\S*)\\b/i': 'Leave',
      '/\\b(librar\\S*|libar\\S*|bookmobil\\S*|book.?mobil\\S*|archiv\\S*)\\b/i': 'Library',
      '/\\b(licen\\S*|lisen\\S*|perm.?t|perm.?ts|perm.?t.?s )\\b/i': 'License',
      '/\\b(operat\\S* sys\\S*|os|osx|os x|((Window\\S*|win) && (95|98|2000|XP\\S*|Vista\\S*|7|8|8.?1|81|10))|windows|mac|macs|mac.?nt.?sh\\S*|linux\\S*|apple\\S*|unix\\S*)\\b/i': 'OperatingSystem',
      '/\\b(option\\S*|choice\\S*|selection\\S*|alternativ\\S*)\\b/i': 'Option ',
      '/\\b(opt.?out|opt\\S*  out|waiv\\S* )\\b/i': 'OptOut',
      '/\\b(paperless|paper.?less|paper.?free|paperfree|( ( paperless|paper.?less|paper.?free|paperfree ) && ( record\\S*|record.?keeping ) ) )\\b/i': 'Paperless',
      '/\\b(paper\\S*|paper.?work\\S*|doc|docs|document\\S*|form|forms|file\\S*|slip|slips )\\b/i': 'Paperwork',
      '/\\b(parking\\S*|park|parked|parking.?lot|parkinglot|carpark\\S*|car.?park\\S*|parking.?garage\\S*)\\b/i': 'Parking',
      '/\\b(mand.?tor\\S*|require\\S*|necessar\\S*|necesar\\S*|compuls.?r\\S*|essenti.?l\\S*|esenti.?l\\S*|obligat\\S*|requis.?t\\S*|((have|has|had|having|need\\S*) && to)|need\\S*|factor\\S*  consider\\S*|must|should)\\b/i': 'Need',
      '/\\b(password\\S*|pass.?word\\S*|passcode|pass.?code\\S*|passkey\\S*|pass.?key\\S*|passwrd\\S*|pw|pwd)\\b/i': 'Password',
      '/\\b(pay\\S*|paid|pay\\S* out\\S*|paid out\\S*|pay\\S* off|paid\\S* off|pay\\S* up|paid\\S* up|pay.?off\\S*|paid.?off\\S*|paying.?off\\S*|pymt\\S*|put\\S* money on\\S*|installment\\S*|instalment\\S* )\\b/i': 'Payment',
      '/\\b(paypal\\S*|pay.?pal\\S* )\\b/i': 'PayPal',
      '/\\b(percent\\S*|ratio|ratios|weigh\\S*|proportion\\S*|distribut\\S* )\\b/i': 'Percentage',
      '/\\b(price\\S*|pricing|cost\\S*|((how much) && (is|are|was|will))|charge\\S*|rate\\S*|cheap\\S*|expens\\S*|fare|fares|worth\\S*|valu\\S* )\\b/i': 'Price ',
      '/\\b(process|processes|procedure\\S*|method\\S*|routin\\S*|operation\\S*|action|actions|step|steps|way to|ways to)\\b/i': 'Process',
      '/\\b(area\\S*|region\\S*|section\\S*|sector\\S*|territor\\S*|vicinit\\S*|zone\\S*|district\\S* )\\b/i': 'Region',
      '/\\b(remov\\S*|delet\\S*|elim\\S*|eras\\S*|extrac\\S*|((take|taking|took) && (out\\S*|away))|drop\\S*|withdr\\S*|with.?dr\\S*|withdrw\\S*|with.?dr.?w\\S*|wd|g.?t\\S* rid of|dispos\\S* of|clean\\S*|clear\\S*|scrub\\S*|sweep\\S*)\\b/i': 'Remove',
      '/\\b(home\\S*|propert\\S*|hous\\S*|houseing\\S*|housing\\S*|apartment\\S*|apt\\S*|apts|condo|condos|cond.?min\\S*)\\b/i': 'Home',
      '/\\b(req|reqs|pre.?req\\S*|prereq\\S*|co.?req\\S*|coreq\\S*|requisit\\S*)\\b/i': 'Prerequisite',
      '/\\b(repeat\\S*|retak\\S*|re.?tak\\S*|redo|re.?do|do over|do.?over\\S*|do again|duplicat\\S* )\\b/i': 'Repeat',
      '/\\b(request\\S*|ask\\S*|ask\\S* for|.?nquir\\S*|demand\\S*|query|queri\\S*|would like|want|wants|wanting|desir\\S*|wish\\S*)\\b/i': 'Request',
      '/\\b(reserv\\S*|book\\S*|secure|secured|securing|hold\\S*|held|layaway\\S*|lay.?away\\S*|set\\S* asid\\S*  )\\b/i': 'Reserve',
      '/\\b(safe\\S* deposit box\\S*|sdb\\S*|S.?D.?B\\S*|deposit box\\S*|safe\\S* box\\S*|safe\\S* deposit\\S*|vault\\S*|locker\\S*|secur\\S* box\\S*|safe|safes)\\b/i': 'SafeDepositBox',
      '/\\b(schedul\\S*|s.?edul\\S*|sheldul\\S*|sked\\S*|timetable\\S*|time.?table\\S*|agenda\\S*)\\b/i': 'Schedule',
      '/\\b(serv\\S*|sevric\\S* )\\b/i': 'Service',
      '/\\b(share\\S*|sharing|joint|communal\\S*|collectiv\\S*|mutu.?l\\S*|coop|co.?op|cooperat\\S*|co.?operat\\S*|collaborat\\S*|collab|common|spousal)\\b/i': 'Share',
      '/\\b(show|shows|showed|showing|shown|depict\\S*|demonstra\\S*|proof\\S*|prove\\S*|proove\\S*|proving|prooving|exhibit\\S*|display\\S*|present\\S*|reveal\\S*|illustrat\\S*|disclos\\S*|explain\\S*|indicat\\S*)\\b/i': 'Show ',
      '/\\b(sign.?in|login|log.?in|((log\\S*|sign\\S*) && (in|on))|((start\\S*|begin\\S*|open\\S*|initiat\\S*) && session\\S*))\\b/i': 'SignIn',
      '/\\b(sign.?off|sign.?out|logoff|log.?off|logout|log.?out|((log\\S*|sign\\S*) && (out|off))|((end\\S*|stop\\S*|clos\\S*) && session\\S*))\\b/i': 'SignOff',
      '/\\b(simil\\S*|equiv.?l.?nt\\S*|equal\\S*|interchang\\S*|inter.?chang\\S*|is like|was like|are like|like each other|be like|were like|the same|same as|alike\\S*|comp.?r.?bl\\S*|compr.?bl\\S*|compat.?bl\\S* )\\b/i': 'Similar',
      '/\\b(skip\\S*|avoid\\S*|miss\\S*|forget\\S*|omit\\S*|absen\\S*|default\\S*|bypass\\S*|abstain\\S*|avert\\S*|circumv\\S*|deflect\\S*|desist\\S*|elud\\S*|evad\\S*|shirk\\S*|sidestep\\S*|side.?step\\S*|bail\\S*|cop.?out|skip\\S* out\\S* on)\\b/i': 'SkipAvoid',
      '/\\b(smok\\S*|tobacco\\S*|cigar\\S*|shisha\\S*|hookah\\S*|(smok\\S* && (pipe\\S*|chain\\S*))|vape|vaped|vapori\\S*|vaping|ejuice\\S*|e.?juice\\S*|pipe|cigaret\\S* )\\b/i': 'Smoking',
      '/\\b(social.?media|youtube\\S*|you.?tube|twitter\\S*|instagr.?m\\S*|insta.?gram\\S*|facebook\\S*|face.?book\\S*|.?log\\S*|tumblr\\S*|snapchat\\S*|snap.?chat\\S*|tweet\\S*|pinterest\\S*|linkedin|linked.?in|google.?)\\b/i': 'SocialMedia',
      '/\\b(software\\S*|soft.?ware\\S*|program\\S*|software licen\\S*|app|apps )\\b/i': 'Software',
      '/\\b(special\\S* need\\S*|disabl\\S*|disabil\\S*|paraly\\S*|parali\\S*|handicap\\S*|handi.?cap\\S*|blind|deaf|wheel.?chair\\S*|wheelchair\\S*|((phys\\S*|mental\\S* ) && disab\\S*) )\\b/i': 'SpecialNeeds',
      '/\\b(status\\S*|state|states|condition\\S*|currently at)\\b/i': 'Status ',
      '/\\b(stol\\S*|steal\\S*|steel\\S*|robbed|robed|robs|rob|burgl\\S*|break\\S* in\\S*|broke\\S* in\\S*|rip\\S* off|lifted|pick.?pocket\\S*|pickpocket\\S*|theft|thief\\S*|theif \\S*|thiev\\S*|theiv\\S*|crook|pirat\\S*|((someone|somebody|some.?one|some.?body) && (took|take\\S*)))\\b/i': 'Stolen',
      '/\\b(stop\\S*|end|ends|ending|ended|conclud\\S*|conclus\\S*|put\\S* a stop to|put\\S* an end to|halt\\S*|pause\\S*|pausi\\S*|cease\\S*|ceasing  )\\b/i': 'Stop',
      '/\\b(stud.?nt\\S*|schol.?r|schol.?rs|pup.?l\\S*)\\b/i': 'StudentGeneral',
      '/\\b(Weekday\\S*|week.?day\\S*|week|weeks|weekly|Monday\\S*|Mon|Mon.?|Tuesday\\S*|Tue|Tue.?|Tues.?|Wednesday\\S*|Wensday\\S*|Wed|Wed.?|Thursday\\S*|Thur|Thur.?|Thurs.?|Friday\\S*|Fri|Fri.? )\\b/i': 'Weekdays',
      '/\\b(weekend\\S*|week.?end\\S*|saturday\\S*|sat|sat.?|sunday\\S*|sun|sun.? )\\b/i': 'Weekend',
      '/\\b(wireles\\S*|wire.?les\\S*|wifi\\S*|wi.?fi\\S* )\\b/i': 'Wireless',
      '/\\b(can not|can.?t|cant|cannot|canot|couldn.?t|could not|unable|not able|.?ncap.?ble|inable\\S*|inabil\\S*|un.?able\\S*|unabil\\S*|.?nadequat\\S*|helpless\\S*|powerless\\S*|unfit\\S*|incompetent\\S*|unqualif\\S* )\\b/i': 'Unable',
      '/\\b(unavailab\\S*|close\\S*|closing\\S*|occupy|occupi\\S*|.?naccess\\S*|taken|absen\\S*|omit\\S*|busy|engaged )\\b/i': 'Unavailable',
      '/\\b(use|uses|using|usage\\S*|run|runs|running|operat\\S*|ut.?l.?z\\S*|ut.?l.?s\\S* )\\b/i': 'Use',
      '/\\b(user\\S*|end.?user\\S*|customer\\S*|client\\S*|caller\\S*|member\\S*|buyer\\S*|purchaser\\S* )\\b/i': 'User',
      '/\\b(((secur\\S*|secret\\S*) && (question\\S*|queston\\S*|answer\\S*|respons\\S*))|answer to the question|((fav\\S*|title) && (book|books|movie\\S*|food\\S*))|mother\\S* maid\\S* name\\S*|((pet|pet.?s|dog|dog.?s|cat|cat.?s) && (name|first|1st|1 st))|(city && born))\\b/i': 'SecurityQuestion',
      '/\\b(knowledge.?base\\S*|kb|content manag\\S* system\\S*|CMS)\\b/i': 'KnowledgeBase',
      '/\\b(certific.?t\\S* )\\b/i': 'Certificate',
      '/\\b(backup\\S*|back.?up\\S*|back\\S* up\\S*)\\b/i': 'Backup',
      '/\\b(clean\\S*|sanit\\S*|wash\\S*|clear\\S*|scrub\\S*|wipe\\S*)\\b/i': 'Clean',
      '/\\b(brit\\S*|england\\S*|GB|great brit\\S*|north\\S* irel.?nd|scotl.?nd|uk|u.?k\\S*|united.?kingdom|wales|brexit\\S*)\\b/i': 'Britain',
      '/\\b(list\\S*|record\\S*|checklist\\S*|check.?list\\S*|directory\\S*|directories|catalog\\S*|index\\S*|tall.?\\S* )\\b/i': 'List',
      '/\\b(gov\\S*|gvmt|gvmnt|gov.?t|congress\\S*|parl.?.?m.?nt\\S*|parl.?m.?nt\\S*)\\b/i': 'Government',
      '/\\b(image\\S*|screenshot\\S*|screen.?shot\\S*|screen.?view\\S*|screen|screens|screencap\\S*|screen.?cap\\S*|picture|screen.?pic\\S* )\\b/i': 'Image',
      '/\\b(hard.?drive\\S*|hard disk|hard disk drive\\S*|hdd|hd|harddrive\\S*)\\b/i': 'HardDrive',
      '/\\b(((parent\\S*|matern\\S*|patern\\S*|mat) && (leave|time.?off|absen\\S*))|maternity|paternity)\\b/i': 'ParentalLeave',
      '/\\b(photocop\\S*|photo\\S* cop\\S*|copy|copies\\S*|xer\\S*|print\\S* cop\\S*|scan\\S*)\\b/i': 'Photocopy',
      '/\\b(pos|p.o.s\\S*|point\\S* of sale\\S*|point.?of.?sale\\S*)\\b/i': 'PointOfSale',
      '/\\b(storag\\S*|storing|repositor\\S*|cache|depositor\\S*|depot\\S*)\\b/i': 'Storage',
      '/\\b(vacation\\S*|vacay|vaca|trip|trips|getaway\\S*|get.?away\\S*|travel\\S*|voyage\\S*|excursion\\S*|sight.?see\\S*|sightsee\\S*|tour\\S*)\\b/i': 'Vacation ',
      '/\\b(vaccine\\S*|vacin\\S*|shots|shot|immuni.?\\S*|imuni.?\\S*|inoculat\\S*|innoculat\\S*|flu.?jab\\S*|flujab\\S*)\\b/i': 'Vaccine ',
      '/\\b(verif\\S* by visa\\S*|verifiedbyvisa\\S*|VBV|V.?B.?V.?|VB Visa|V.?B.? Visa|VBVisa)\\b/i': 'VerifiedVisa',
      '/\\b(view\\S*|see|sees|saw|seeing|look\\S*|observ\\S*|watch\\S*|check.?out  )\\b/i': 'View',
      '/\\b(virus\\S*|spy.?ware\\S*|spyware\\S*|adaware\\S*|spybot\\S*|hack\\S*|malware\\S*|mal.?ware\\S*|bot|bots|webcrawl\\S*|web.?crawl\\S*|junkware\\S*|junk.?ware\\S*)\\b/i': 'VirusSpyware',
      '/\\b(stream\\S*|netflix\\S*|cravetv|crave.?tv|amazon.?prime\\S*|amazon\\S* prime\\S*|amazon\\S* instant\\S* video\\S*|hulu\\S*|hulu plus|sling|slingbox|sling.?box\\S*|playstation vue\\S*|hbo now|youtub\\S*|you.?tub\\S*|(netflix && chill))\\b/i': 'StreamingService',
      '/\\b(holiday\\S*|((New Year\\S*|Islander|Family|Louis Riel|St Patrick\\S*|St George\\S*|Victoria|National Patriotes|National Aboriginal|St Jean Baptiste|Discovery|Canada|Memorial|Nunavut|Labour|labor|Remembrance|Boxing|memorial|columbus|Martin Luther King|MLK|snowflake) && day)|Good Friday|Easter Monday|Easter|F.?te Nationale|Civic Holiday\\S*|Thanksgiving\\S*|Christmas\\S*|x.?mas|xmas|hanukka\\S*|hanuka\\S*|chanukka\\S*|chanuka\\S*|new year\\S*|july\\S* 4\\S*|may 24\\S*|pres\\S* day|prez day|washington\\S* birthday|long weekend\\S*|bank\\S* holiday)\\b/i': 'Holidays',
      '/\\b(print\\S*)\\b/i': 'Print',
      '/\\b(natur\\S* disast\\S*|avalan.?h\\S*|landslid\\S*|tornado\\S*|.?.?unami\\S*|flood\\S*|hurrican\\S*|earthquak\\S*|earth.?quake\\S*|volcan\\S*|tidal.?wav\\S*|sinkhol\\S*|blizz.?rd\\S*)\\b/i': 'NaturalDisaster',
      '/\\b(foreign\\S* languag\\S*|languag\\S*|dialect\\S*|english\\S*|eng|arabic\\S*|chines\\S*|mandarin\\S*|canton\\S*|germ.?n\\S*|greek\\S*|french\\S*|itali.?n\\S*|japanes\\S*|korean\\S*|latin\\S*|languag\\S*|portug.?s\\S*|portug.?.?s\\S*|russian\\S*|spanish\\S*|ukranian\\S*|vietnames\\S*|anglais\\S*|fran.?ais\\S*|espa.?ol\\S*|klingon)\\b/i': 'Languages',
      '/\\b(manager\\S*|supervis.?r\\S*|boss\\S*|superi.?r\\S*|direct.?r|direct.?rs|employ.?r\\S*|superintend.?nt\\S*|team.?lead\\S*|kelly)\\b/i': 'Manager',
      '/\\b(configur\\S*|setup\\S*|set.?up\\S*|set\\S* up\\S*|set|sets|setting\\S*|seting\\S*|layout\\S*|reset\\S*|reconfig\\S*|enabl\\S*|instal\\S*)\\b/i': 'Configure',
      '/\\b(foul\\S* language\\S*|bad word\\S*|stupid\\S*|swear|swears|swearing|bull\\S*|fuck\\S*|weed|curse word\\S*|fuck\\S*|shit\\S*|ret.?rd\\S*|dumb\\S*|sucking\\S*|sucker\\S* piss\\S*|hell|damn\\S*|dick\\S*|puss\\S*|vagin\\S*|penis\\S*|boob\\S*|butt\\S*|ass|ef\\S* you\\S*|assh\\S*|cock\\S*|sex|sexy|sexual|porn\\S*|balls|scrotum|tit|tits|titties|cunt|bitch\\S*|dick\\S*|bastard\\S*|whore\\S*|slut\\S*|pimp\\S*|fag\\S*|queer\\S*|nigg\\S*|chink|poop\\S*|mast.?rbate\\S*|whack off|jack off|crap\\S*|jerk off|jackass\\S*|jack ass|horn\\S*|fart\\S*|blow job|blowjob|booger\\S*|schlong\\S*|weiner\\S*|wiener\\S*|boner\\S*|hardon|hard-on|Viagra|virgin|cooch\\S*|get laid|kkk|suck\\S*|willy|winky\\S*|winkie\\S*|chick.?nf.?ck.?r\\S*|homo|chik.?nf.?.?.?r\\S*|chik.?nf.?.?k\\S*|chick\\S* f.?.?.?.?r\\S*|chik\\S* f.?.?.?r\\S*|suck|sucks\\S*|suckr|sucker\\S*|you suck|u suck|ch.?ck.?nsh.?t\\S*|ch.?ck.?n\\S* sh.?t\\S*|ch.?ck.?n.?sh.?t\\S*|nipple\\S*|are you gay|are u gay)\\b/i': 'FoulLanguage',
      '/\\b(housekeep\\S*|house.?keep\\S*|clean\\S*|scrub\\S*|saniti\\S*|wash\\S*|vacu\\S*|vaccu\\S*|dust\\S*|sweep\\S*|mop|broom\\S*|maid\\S*)\\b/i': 'Housekeeping',
      '/\\b(revers\\S*|revert\\S*|undo|un.?do|overturn\\S*|counter\\S*|turn\\S* around|rollback\\S*|roll\\S* back\\S*|go\\S* back\\S*|return\\S* to)\\b/i': 'Reverse',
      '/\\b(try\\S*|trial\\S*|attemp\\S*|practi.?e\\S*|practis\\S*|practic\\S*|experiment\\S*)\\b/i': 'Try',
      '/\\b(verif\\S*|confirm\\S*|authenticat\\S*|attest\\S*|check\\S*|double.?check\\S*|doublecheck\\S*|((mak\\S*|made) && ( certain\\S*|sure\\S*))|prove|proving|proved|proven|proves|proof|proov\\S*|validat\\S*|corroborat\\S*)\\b/i': 'Verify',
      '/\\b(determin\\S*|calcul\\S*|((find\\S*|figur\\S*|found|work\\S*) && out)|measur\\S*|gauge|count|tally)\\b/i': 'Determine',
      '/\\b(frequen\\S*|cycl\\S*|peri.?d\\S*|int.?rv.?l\\S*|times|oft.?n|regul.?r\\S*|recur\\S*|s.?m.?ster\\S*)\\b/i': 'Frequency',
      '/\\b(find\\S*|found|search\\S*|locate\\S*|locating|look\\S* for|look\\S* up|lookup\\S*|look.?up\\S*|hunt\\S*|track\\S*  down|track\\S*|tracking|brows\\S*|perus\\S*|direction\\S*|googl\\S*)\\b/i': 'Find',
      '/\\b(handl\\S*|manag\\S*|deal\\S* with|oversee\\S*|tak\\S* care of|approach\\S*|cop\\S* with|attend\\S* to)\\b/i': 'Handle',
      '/\\b(addons|add.?ons)\\b/i': 'AddOns',
    },
  };
  return regex;
};

export default synonymsSet3;
//      '/\\b(computer\\S*|cpu\\S*|pc\\S*|mac\\S*|personal comp\\S*|comp|desktop\\S*|desk.?top\\S*|laptop\\S*|lap.?top\\S*|notebook\\S*|note.?book\\S*|macbook\\S*|mac.?book\\S*||((notebook\\S*|note.?book\\S*|laptop\\S*|lap.?top\\S*|portab\\S*) && (pc\\S*|computer\\S*))|comp\\S* manufact\\S*|apple|dell|asus|acer|toshiba|hp|compaq|IBM|thinkpad\\S*)\\b/i': 'Computer',
//      '/\\b(overdraft\\S*|over.?draft\\S*|overrun\\S*|over.?run\\S*|over.?dr.?w\\S*|overdr.?w\\S*|OP|O.?P.?|NSF|N.?S.?F.?|OPFB|O.?P.?F.?B.?|ODF|O.?D.?F.?|((overdraft\\S*|over.?draft\\S*|overrun\\S*|over.?run\\S*|over.?dr.?w\\S*|overdr.?w\\S*) && (protect\\S*|facilit\\S*))|(( not enou\\S*|have enou\\S*|has enou\\S*|not enuf\\S*|have enuf\\S*|has enuf\\S*|not suffic\\S*|not sufic\\S*|isn\\S* enough|non.?suffic\\S*|non.?sufic\\S*|non suffic\\S*|non sufic\\S*|unsuffic\\S*|unsufic\\S*|insuffic\\S*|insufic\\S* ) && Money)|((bounc\\S*|did not clear|will not clear|won.?t clear|didn.?t clear|did not go through|didn.?t go through|will not go through|won.?t go through|return\\S* ) && Cheque))\\b/i': 'Overdraft ',
