const synonyms = () => {
  const regex = {
    type: 'regex-replace',
    mappings: {
      '/\\b(beneficiar\\S*|ben.?fitiar\\S*|inherit\\S*|heir\\S*|legatee\\S*|asset recipient)\\b/i': 'Beneficiary',
      '/\\b(book|books|textbook\\S*|text.?book\\S*|coursebook\\S*|coursenote\\S*|course note\\S*|novel|novels|((class\\S*|course\\S*|read\\S*|school\\S* ) && (material\\S*|book\\S*|note\\S*)))\\b/i': 'Book',
      '/\\b(addres\\S*|adres\\S*|location)\\b/i': 'Address',
      '/\\b(depart\\S*|takeoff\\S*|take.?off\\S*|((tak\\S*|took) && off\\S*)|launch\\S*|embark\\S*|(set\\S* && (out\\S*|forth\\S*)))\\b/i': 'Depart ',
      '/\\b((person\\S*|my) && (info\\S*|data|detail\\S*))\\b/i': 'PersonalInformation',
      '/\\b(phone\\S*|telephon\\S*|cell\\S*|mobile\\S*|smartphone\\S*|smart.?phone\\S*|mobil\\S*  devic\\S*|iphone\\S*|i.?phone\\S*|android\\S*|nexus\\S*|blackberr\\S*|black.?berr\\S*|motorola\\S*|samsung\\S*|LG|Sony|HTC)\\b/i': 'Phone',
      '/\\b(plan|plans|scheme\\S*|arrangement\\S*|program\\S*|strateg\\S*|system\\S*|project\\S*)\\b/i': 'Plan',
      '/\\b(police\\S*|policing|cop|cops|constable\\S*|mounty|mounties|detectiv\\S*|law enfor\\S*|officer|officers|patrol\\S*|authorities|fuzz|narc )\\b/i': 'Police',
      '/\\b(positiv\\S*|good|great\\S*|well|ok|okay|right\\S*|correct\\S*|ideal\\S*|perfect\\S*|fantastic\\S* )\\b/i': 'Positive ',
      '/\\b(pre.?author\\S* pay\\S*|preauthor\\S* pay\\S*|pre.?approv\\S* pay\\S*|preapprov\\S* pay\\S*|pap|p.?a.?p.?|pad|p.?a.?d.?|papp|p.?a.?p.?p.?|auto.?withdraw\\S*|autowithdraw\\S*|auto.?pay|auto\\S* pay\\S*|autopay\\S*|auto.?debit\\S*|auto\\S* debit\\S* autodebit\\S*|direct.?withdraw\\S*|direct.?pay\\S*|directpay\\S*|directdebit\\S*|direct.?debit\\S*|((pre.?author\\S*|preauthor\\S*|pre.?approv\\S*|preapprov\\S*|direct\\S*|auto\\S*) && (pay\\S*|debit\\S*|pay\\S* plan\\S*|withdraw\\S*)))\\b/i': 'PreAuthorizedPayment',
      '/\\b(promo\\S*|incentiv\\S*|deal\\S*|special\\S*|bonus\\S* )\\b/i': 'Promotion',
      '/\\b(protec\\S*|safe\\S*|safeguard\\S*|safe.?guard\\S*|guard\\S*|shelter\\S*|preserv\\S*|as.?lum\\S*|refuge\\S*|sanctu\\S*|secur\\S* )\\b/i': 'Protect',
      '/\\b(rank\\S*|ordin.?nc\\S*|order\\S*|place\\S*|standing\\S*|position\\S*|hierarch\\S*|pedigree\\S*|stature\\S*)\\b/i': 'Rank',
      '/\\b(realestate|real.?estate|realtor\\S*)\\b/i': 'RealEstate',
      '/\\b(redeem\\S*|redem\\S*|cash\\S* in|cashed)\\b/i': 'Redeem',
      '/\\b(special health servic\\S*|special servic\\S*|profes\\S* servic\\S*|massag\\S*|masag\\S*|rmt\\S*|nat.?r.?path\\S*|nat.?rpath\\S*|ch.?rop\\S*|acupun\\S*|homeopath\\S*|ps.?chol.?g\\S*|ps.?chia\\S*|coun.?.?l\\S*|therap\\S*|rehab\\S*)\\b/i': 'SpecialHealthServices',
      '/\\b(specific\\S*|certain\\S*|particul.?r\\S*|set|definite\\S*|finite\\S*|distinct\\S*|exact\\S*|explic.?t\\S*|precis\\S*|fixed|decided|established )\\b/i': 'Specific',
      '/\\b(spous\\S*|spouc\\S*|partner\\S*|wife\\S*|wiv\\S*|husban\\S*|hubby\\S*|partner\\S*|domestic partner\\S*|common  law\\S*|commonlaw|common.?law  partner\\S* )\\b/i': 'Spouse',
      '/\\b(opt.?in|(opt\\S* && in)|participat\\S*)\\b/i': 'OptIn',
      '/\\b(alter\\S*|chang\\S*|edit|editing|exchang\\S*|((find\\S*|found|pick\\S*|switch\\S*) && another)|make\\S* change\\S*|modif\\S*|revis\\S*|switch\\S*|up date|updat\\S*|up.?dat\\S*|upgrad\\S*|convert\\S*|conversion)\\b/i': 'Modify',
      '/\\b(claim\\S*|claim form\\S*)\\b/i': 'Claim',
      '/\\b(sport\\S*|athlet\\S*|athelet\\S*|game\\S*|team\\S*|coach\\S*|archery\\S*|badm.?nt.?n\\S*|baseball\\S*|base.?ball\\S*|basket.?ball\\S*|basketball\\S*|bowling|crosscountry\\S*|cross.?country\\S*|equestri.?n\\S*|fencing\\S*|fishing|field.?hockey\\S*|fieldhockey\\S*|foot.?ball\\S*|football\\S*|golf\\S*|gymnastic\\S*|handball\\S*|hockey\\S*|ice.?hockey\\S*|icehockey\\S*|l.?cros\\S*|rifle\\S*|rowing\\S*|rugby\\S*|ski|skiing\\S*|socc.?r\\S*|softball\\S*|squash\\S*|swim\\S*|sync\\S* swim\\S*|tenn.?s\\S*|(track\\S* && ( field\\S*|indoor\\S*|outdoor\\S* ) )|volleyball\\S*|volley.?ball\\S*|waterpolo\\S*|water.?polo\\S*|wrestling\\S*|quidditch\\S*)\\b/i': 'Sports',
      '/\\b(person|persons|people\\S*|human\\S*|citizen\\S*|individual\\S*|somebod\\S*|some.?body\\S*|anybody\\S*|any.?bod\\S*|anyone\\S*|any.?one\\S*|someone\\S*|some.?one\\S*|everybod\\S*|every.?bod\\S*|everyone\\S*|every.?one\\S*|fr.?.?nd\\S*|frind\\S*|buddy\\S*|buds|buddies|chum\\S*|pal|pals|pal.?s|companion\\S*|male\\S*|female\\S*)\\b/i': 'Person',
      '/\\b(provid\\S*|provis\\S*|offer\\S*|ofer|g.?ve|given|giving)\\b/i': 'Provide',
      '/\\b(purchas\\S*|buy\\S*|order\\S*|reorder\\S*|bought\\S*)\\b/i': 'Purchase',
      '/\\b(s.?.?ol.?r.?.?ip\\S*|s.?.?oll.?r.?.?ip\\S*|((student\\S*|financ\\S*) && award\\S*)|bursar\\S*|grant|grants )\\b/i': 'Scholarship',
      '/\\b(school\\S*|uni|universit\\S*|coll.?ge\\S*|col.?ge\\S*|institution\\S*|campus\\S*|high.?school\\S*)\\b/i': 'School',
      '/\\b((school|term|midterm\\S*|mid.?term\\S*|reading\\S*|spring\\S*|summer\\S*|winter\\S*|fall\\S*|march\\S*|feb\\S*|december\\S*|dec) && ( break\\S*|holiday\\S*|vacation\\S*|week\\S* ) )\\b/i': 'SchoolBreak',
      '/\\b(season\\S*|spring\\S*|summer\\S*|fall|autum\\S*|winter\\S* )\\b/i': 'Seasons',
      '/\\b(sell\\S*|sold|peddl\\S*|pitch\\S*|vend\\S*|retail\\S*|resell\\S*|resal\\S*|re.?sell\\S*|re.?sal\\S*|merchan\\S*)\\b/i': 'Sell',
      '/\\b(senior\\S*|senior.?cit\\S*|6.?.?year\\S*|7.?.?year\\S*|((old\\S*|retire\\S*|elder\\S*) && (people|person|man|men|gentlem.?n\\S*|gentle.?m.?n\\S*|wom.?n|lady|ladies))|elder\\S*|geezer\\S*|retiree\\S*|over.?6.?|over.?7.?|over.?sixty\\S*|over.?seventy\\S* )\\b/i': 'SeniorCitizen',
      '/\\b((s.?rv\\S* lev.?l (agr\\S*|commit\\S*))|SLA|S.L.A.|SLAS|SLA.?S )\\b/i': 'ServiceLevelAgreement',
      '/\\b(test)\\b/i': 'Test',
      '/\\b(before\\S*|ahead\\S*|ahead.?of|in.?advance\\S*|pri.?r.?to\\S*|precede|precedes|preceding|sooner.?th.?n|previous\\S*|previous.?to|early|earli\\S*|pre.?matur\\S*|prematur\\S*|advance)\\b/i': 'Before',
      '/\\b(begin\\S*|commenc\\S*|comenc\\S*|start\\S*|initia\\S*|launch\\S*|get\\S* going|kickoff\\S*|kick.?off\\S*|kick\\S* off|set\\S* forth\\S*|onset\\S*|boot\\S*|reboot\\S*|power\\S* on|activat\\S*|introduc\\S* )\\b/i': 'Begin',
      '/\\b(borrow\\S*|rent\\S*|lease\\S*|leasing )\\b/i': 'Borrow',
      '/\\b(brochure\\S*|pamfl\\S*|pamphl\\S*|cat.?l.?g\\S*|leaflet\\S*|booklet\\S*|flyer\\S*|flier\\S*|newsletter\\S*|news.?letter\\S*|bull.?tin\\S*|press.?release\\S*)\\b/i': 'Brochure',
      '/\\b(browser\\S*|netscape|internet explorer|ie|i.e.\\S*|microsoft net\\S* sca\\S*|aol|mozilla\\S*|firefox\\S*|fire.?fox\\S*|safari\\S*|chrome\\S*|microsoft edge|ms edge|edge)\\b/i': 'Browser',
      '/\\b(cable|cablevision|cable.?vision|cable.?tv|tv\\S*|t.v.|television\\S*|cabletv|cable.?telev\\S* )\\b/i': 'CableTV',
      '/\\b(call|calls|called|calling|ring|rings|ringing|dial\\S*|phone\\S*|phoning)\\b/i': 'Call ',
      '/\\b(canada\\S*|canadi.?n\\S*|cdn|candi.?n\\S*)\\b/i': 'Canada',
      '/\\b(charit\\S*|not.?for.?profit\\S*|nfp\\S*|non.?profit\\S*|nonprofit\\S*|philanth\\S*|donat\\S*|donor\\S*|endow\\S* )\\b/i': 'Charity',
      '/\\b(cheque\\S*|check|checks|cheqs|cheqeu|cheqeus|chq\\S*|chk\\S*|chequing|checking )\\b/i': 'Cheque ',
      '/\\b(club\\S*|alianc\\S*|allianc\\S*|association\\S*|asociation\\S*|faction\\S*|league\\S*|societ\\S*|union\\S*)\\b/i': 'Club',
      '/\\b(code\\S*|coding)\\b/i': 'Code',
      '/\\b(combin\\S*|consol\\S*|merg\\S*|unite\\S*|uniting|unif\\S*|blend\\S*|mix\\S*|pool\\S*|amalg\\S* )\\b/i': 'Combine ',
      '/\\b(company\\S*|companies|busines\\S*|b.?snes\\S*|buisnes\\S*|biz|agenc\\S*|firm\\S*|organi.?ation\\S*|org|corporat\\S*|association\\S*|guild\\S*|enterpri.?\\S*|commercial\\S* )\\b/i': 'Company',
      '/\\b(complet\\S*|whole\\S*|entir\\S*|all|full\\S*|total\\S* )\\b/i': 'Complete',
      '/\\b(connect\\S*|hook\\S* up|hook.?up\\S*|hookup\\S*|( ( turn\\S*|connect\\S*|get\\S* ) && ( back on|on again ) )|reconnect\\S*|recconnect\\S*|re.?connect\\S*|reconect\\S*|re.?conec\\S*|((switch\\S*|turn\\S* ) && on)|start\\S* up)\\b/i': 'ConnectReconnect',
      '/\\b(contact\\S*|communica\\S*|comunica\\S*|reach\\S*|talk\\S*|speak\\S*|((speak\\S*|talk\\S*|communicat\\S*|connect\\S*) && (to|with))|in.?touch|touch.?base|inform|informs|informed|informing|advise\\S*|advising|tell\\S*|told )\\b/i': 'Contact',
      '/\\b(contract\\S*|agreement\\S*|contrct\\S*|rider\\S*)\\b/i': 'Contract',
      '/\\b(copay\\S*|co.?pay\\S* )\\b/i': 'CoPay',
      '/\\b(cours\\S*|coars\\S*|cors\\S*|subject\\S*|class|classes|clas|calss\\S*)\\b/i': 'Course',
      '/\\b(creat\\S*|mak\\S*|made|establish\\S*|build\\S*|generate\\S*|generating\\S*|produce\\S*|producing|construc\\S*|invent\\S* )\\b/i': 'Create',
      '/\\b(credit.?card\\S*|credit\\S*|visa|mastercard|master card|amex|american express|diners club|diners card|discover|mbna|tang.?rine )\\b/i': 'CreditCard',
      '/\\b(download\\S*|down.?load\\S*|down load\\S*|dl|d.l. )\\b/i': 'Download ',
      '/\\b(freshm.?n\\S*|frosh\\S*|first.?year\\S*|firstyear\\S*|freshie\\S*|((first.?year\\S*|firstyear\\S*) && student\\S*) )\\b/i': 'StudentFreshman',
      '/\\b(((second\\S*|vacation\\S*|vacay|temp\\S*|rent\\S*) && (home\\S*|hous\\S*|propert\\S*))|cottag\\S*|chalet\\S*|cabin\\S*|RV|rec\\S* vehicl\\S*|mobil\\S* home\\S*|trailer\\S*)\\b/i': 'SecondaryHome',
      '/\\b(bank\\S* machine\\S*|bank.?machine\\S*|bankmachine\\S*|ATM\\S*|A.T.M\\S*|ATM machine\\S*|auto\\S* teller\\S*|auto\\S* teller\\S* machine\\S*|ABM\\S*|A.B.M\\S*|ABM machine\\S*|auto\\S* bank\\S* machine\\S*|cash\\S* machine\\S*|cash.?machine\\S*|cash\\S* d.?spens.?r\\S*|cash.?d.?spens.?r\\S*|green.?machine\\S* )\\b/i': 'BankMachine',
      '/\\b(big\\S*|huge\\S*|gigant\\S*|giant\\S*|enormous\\S*|hum.?ngous\\S*|large\\S*|long\\S*|considerabl\\S*|heavy|heavi\\S*)\\b/i': 'Big',
      '/\\b(choos\\S*|pick\\S*|select|selects|selected|selecting|decid\\S*|declar\\S*|elect\\S*|chose)\\b/i': 'Choose',
      '/\\b(((grad\\S*|master\\S*) && (student\\S*|scholar|scholars|school\\S*|program\\S*))|grad|master\\S*|phd\\S*|ph.?d|doctorate\\S*|post.?doc\\S*|MA|MS|MBA|LLB|MD)\\b/i': 'StudentGrad',
      '/\\b(((undergrad\\S*|under.?grad\\S*) && student\\S*)|undergrad\\S*|under.?grad\\S*|soph\\S*|juni.?r\\S*|seni.?r\\S*|((1st|first|2nd|second|3rd|third|4th|fourth) && year\\S*)|1st.?year\\S*|2nd.?year\\S*|3rd.?year\\S*|4th.?year\\S*)\\b/i': 'StudentUndergrad',
      '/\\b(submi\\S*|send\\S*|sent|submit\\S*|file|filing|((send\\S*|sent|hand\\S*) &&  (in|over))|drop.?off|drop\\S*  off|deliver\\S* )\\b/i': 'SubmitSend',
      '/\\b(summar\\S*|sumar\\S*|report\\S*|abstract\\S*|prospect.?s\\S*|synops\\S*|spec|specs)\\b/i': 'Summary ',
      '/\\b(survey\\S*|audit|audits|auditing\\S*|audited|poll|polls|polling|polled )\\b/i': 'Survey',
      '/\\b(tablet\\S*|surface\\S*|microsoft.?surface\\S*|e.?book\\S*|ebook\\S*|electronic.?book\\S*|eread\\S*|e.?read\\S*|Kindle\\S*|Nook\\S*|Kobo\\S*|ipad\\S*|ipod\\S*|vtech|samsung tab\\S* )\\b/i': 'Tablet',
      '/\\b(tax\\S*|duty|duties|levy|levies|tariff\\S*|excise\\S*|harmon\\S* sale\\S* tax\\S*|HST\\S*|H.?S.?T\\S*|(good\\S* && servic\\S* && tax\\S*)|GST\\S*|G.?S.?T\\S* )\\b/i': 'Tax',
      '/\\b(teacher\\S*|educat.?r\\S*|instruct.?r\\S*|tutor|tutors|train.?r\\S*|prof|profs|profess.?r\\S*|proffes.?r\\S*|profes.?r\\S*|facult\\S* )\\b/i': 'Teacher',
      '/\\b(ticket\\S*|pass|passes|invitation\\S*|token\\S* )\\b/i': 'Ticket',
      '/\\b(time.?off|timeoff|sabbatical\\S*|sabatical\\S*|(leave of && (absen\\S*|abcen\\S*))|((stat\\S*|paid|official|recognize\\S*) && (((time\\S*|day\\S*) && off)|leave\\S*|holiday\\S*)))\\b/i': 'TimeOff',
      '/\\b(max|maxim\\S*|most)\\b/i': 'Maximum',
    },
  };
  return regex;
};

export default synonyms;
