package com.tfs.learningsystems.ui.nlmodel.model;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.swagger.annotations.ApiModelProperty;
import java.util.List;
import lombok.Data;

@Data
@JsonSerialize
public class TFSModel {

  @ApiModelProperty(readOnly = true, value = "internal id generated by MWB", example = "12")
  private String id;
  @ApiModelProperty(required = true, value = "model name", example = "root_intent")
  private String name;
  @ApiModelProperty(readOnly = true, value = "version of the model", example = "12")
  private Integer version;
  @ApiModelProperty(value = "model id", example = "233")
  private String modelId;
  @ApiModelProperty(value = "user id who created the model", example = "ml_user")
  private String userId;
  @ApiModelProperty(value = "config id to be used for model", example = "1")
  private String configId = "1";
  @ApiModelProperty(hidden = true, value = "project id", example = "561")
  private String projectId;
  @ApiModelProperty(value = "model description", example = "Root intent model")
  private String description;
  @ApiModelProperty(value = "model created time", example = "1551998097406")
  private Long createdAt;
  @ApiModelProperty(value = "last model updated time", example = "1551998097406")
  private Long updatedAt;
  @ApiModelProperty(value = "list of datasets to be used", example = "159")
  private List<String> datasetIds;
  @ApiModelProperty(value = "type of model to be trained", example = "DIGITAL")
  private String modelType;
  @ApiModelProperty(value = "defines vectorizer_id", example = "1")
  private int vectorizer_id;
  @ApiModelProperty(value = "defines a technology_type", example = "USE base")
  private String technology_type;
  @ApiModelProperty(value = "defines version", example = "1.3")
  private String technology_version;
  @ApiModelProperty(value = "accuracy of completed model ", example = "0.55")
  private String modelAccuracy = null;
  @ApiModelProperty(value = "average weighted f_score of completed model", example = "0.85")
  private String modelWeightedFScore = null;
  @ApiModelProperty(value = "Digital hosted Url", example = "http://qa.modelbuilder.com/digital")
  private String digitalHostedUrl = null;
  @ApiModelProperty(value = "Speech model id reference", example = "21")
  private String speechModelId = null;
  @ApiModelProperty(value = "Speech config id reference", example = "2111")
  private String speechConfigId = "1";

}
