/*******************************************************************************
 * Copyright © [24]7 Customer, Inc. All Rights Reserved.
 *******************************************************************************/
package com.tfs.learningsystems.ui.model;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;


/**
 * ClientDetail
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen",
    date = "2016-10-21T13:18:07.066-04:00")
public class ClientDetail extends Client implements Serializable {

  private static final long serialVersionUID = 1L;

  private String id = null;

  private Long createdAt = null;

  private Long modifiedAt = null;

  private Integer offset = null;

  private String standardClientName = null;

  private String clientDisplayName = null;

  private String appDisplayName = null;

  private List<String> roles = null;

  @ApiModelProperty(hidden = true)
  private Long totalCount = null;

  public ClientDetail id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Numeric string to identify the Client uniquely
   *
   * @return id
   **/
  @ApiModelProperty(value = "unique id generated by MWB", example = "153")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ClientDetail standardClientName(String standardClientName) {
    this.setStandardClientName(standardClientName);
    return this;
  }

  /**
   * Standard clientName
   *
   * @return Standard clientName used accorss the tools
   **/
  @ApiModelProperty(value = "standard clientName used accross the tools", example = "tfsai")
  public String getStandardClientName() {
    return standardClientName;
  }

  public void setStandardClientName(String standardClientName) {
    this.standardClientName = standardClientName;
  }

  public ClientDetail clientDisplayName(String clientDisplayName) {
    this.setClientDisplayName(clientDisplayName);
    return this;
  }

  /**
   * Standard clientDisplayName
   *
   * @return Standard clientDisplayName used accorss the tools
   **/
  @ApiModelProperty(value = "standard clientDisplayName used in client picker to show in MWB ui", example = "247 ai")
  public String getClientDisplayName() {
    return clientDisplayName;
  }

  public void setClientDisplayName(String clientDisplayName) {
    this.clientDisplayName = clientDisplayName;
  }

  public ClientDetail itsAppId(String itsAppId) {
    super.setItsAppId(itsAppId);
    return this;
  }

  public ClientDetail itsClientId(String itsClientId) {
    super.setItsClientId(itsClientId);
    return this;
  }

  public ClientDetail appDisplayName(String appDisplayName) {
    this.setAppDisplayName(appDisplayName);
    return this;
  }

  /**
   * Standard appDisplayName
   *
   * @return Standard appDisplayName used accorss the tools
   **/
  @ApiModelProperty(value = "standard appDisplayName used in client picker to show in MWB ui", example = "aisha")
  public String getAppDisplayName() {
    return appDisplayName;
  }

  public void setAppDisplayName(String appDisplayName) {
    this.appDisplayName = appDisplayName;
  }

  public ClientDetail roles(List<String> roles) {
    this.setRoles(roles);
    return this;
  }

  /**
   * Standard roles
   *
   * @return Standard roles used accorss the tools
   **/
  @ApiModelProperty(value = "roles assigned to the user for clientId, productId", example = "developer")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public ClientDetail createdAt(Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The UTC date time for client creation
   *
   * @return createdAt
   **/
  @ApiModelProperty(readOnly = true, value = "Client creation time", example = "1551998097304")
  public Long getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }

  public ClientDetail modifiedAt(Long modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * Modification time for any attribute update
   *
   * @return modifiedAt
   **/
  @ApiModelProperty(readOnly = true, value = "last modified time for client", example = "1551998097406")
  public Long getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(Long modifiedAt) {
    this.modifiedAt = modifiedAt;
  }

  public ClientDetail offset(Integer offset) {
    this.offset = offset;
    return this;
  }

  /**
   * Get offset
   *
   * @return offset
   **/
  @ApiModelProperty(value = "", hidden = true)
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public ClientDetail totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

  /**
   * Get totalCount
   *
   * @return totalCount
   **/
  @ApiModelProperty(value = "", hidden = true)
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientDetail clientDetail = (ClientDetail) o;
    return Objects.equals(this.id, clientDetail.id)
            && Objects.equals(this.createdAt, clientDetail.createdAt)
            && Objects.equals(this.modifiedAt, clientDetail.modifiedAt)
            && Objects.equals(this.offset, clientDetail.offset)
            && Objects.equals(this.totalCount, clientDetail.totalCount)
            && Objects.equals(this.clientDisplayName, clientDetail.clientDisplayName)
            && Objects.equals(this.standardClientName, clientDetail.standardClientName)
            && Objects.equals(this.appDisplayName, clientDetail.appDisplayName)
            && Objects.equals(this.roles, clientDetail.roles) && super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, modifiedAt, offset, totalCount,
            clientDisplayName, standardClientName, appDisplayName, roles, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    clientDisplayName: ").append(toIndentedString(clientDisplayName)).append("\n");
    sb.append("    standardClientName: ").append(toIndentedString(standardClientName)).append("\n");
    sb.append("    appDisplayName: ").append(toIndentedString(appDisplayName)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}