package com.tfs.learningsystems.ui.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Objects;


/**
 * IntentScore
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-02-21T16:16:07.557-08:00")
public class IntentScore {

  private String intent = null;

  private BigDecimal score = null;

  public IntentScore intent(String intent) {
    this.intent = intent;
    return this;
  }

  /**
   * The intent generated by the model
   *
   * @return intent
   **/
  @ApiModelProperty(required = true, value = "The intent generated by the model")
  public String getIntent() {
    return intent;
  }

  public void setIntent(String intent) {
    this.intent = intent;
  }

  public IntentScore score(BigDecimal score) {
    this.score = score;
    return this;
  }

  /**
   * The score for the corresponding intent
   *
   * @return score
   **/
  @ApiModelProperty(required = true, value = "The score for the corresponding intent")
  public BigDecimal getScore() {
    return score;
  }

  public void setScore(BigDecimal score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntentScore intentScore = (IntentScore) o;
    return Objects.equals(this.intent, intentScore.intent) &&
        Objects.equals(this.score, intentScore.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intent, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntentScore {\n");

    sb.append("    intent: ").append(toIndentedString(intent)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

