swagger: '2.0'
info:
  version: '1.0.0'
  title: Verify
  description: API to verfiy tagged data
host: localhost:8080
basePath: /nltools
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/content/{projectId}/verify:
    post:
      summary: Runs tag verification tests against data for project
      operationId: stats
      tags:
        - post
      parameters:
        - name: projectId
          in: path
          required: true
          description: The id of the project
          type: string
        - name: startIndex
          in: query
          required: false
          description: The start index to fetch the results from
          type: integer
          format: int32
          default: 0
        - name: limit
          in: query
          required: false
          description: The page size of the results starting from the startIndex
          type: integer
          format: int32
          default: 100
        - name: sortBy
          in: query
          required: false
          description: An array of fields to hierarchically sort in order of their apperance in the array
          type: array
          items: multi
          default: normalizedFormGroup:asc
        - name: search
          in : body
          schema:
            $ref: '#/definitions/VerifyRequest'
      responses:
        200:
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/VerifiedTranscriptionsResponse'
        400:
          description: Project does not have a transformed data set.
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Invalid Project id / Specified dataset not associated with project
          schema:
            $ref: '#/definitions/Error'
        500:
          description:  Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        503:
          description: Elasticsearch Service Unavailable
          schema:
            $ref: '#/definitions/Error'
definitions:
  VerifyRequest:
    properties:
      configId:
        type: string
        description: id of the model configuration
      filter:
        $ref: '#/definitions/VerifyRequestFilter'
  VerifyRequestFilter:
      properties:
        onlyConflicts:
          type: boolean
          description: Return only transcriptions with conflicting intent tags
          default: false
        datasetIds:
          type: array
          items:
           type: integer
  VerifiedTranscriptionsResponse:
    properties:
      startIndex:
        type: integer
        description: The startIndex sent in the request
      limit:
        type: integer
        description: The limit sent in the request
      total:
        type: integer
        format: int64
        description: Total unique transcriptions that fall into the search criteria
      transcriptionList:
        type: array
        items:
          $ref: '#/definitions/VerifiedTranscriptionDocument'
  VerifiedTranscriptionDocument:
    properties:
      intent:
        type: string
      suggestedIntent:
        type: string
      intentConflict:
        type: boolean
      intents:
        type: array
        items:
           type: integer
      documentCount:
        type: integer
        format: int64
      transcriptionHash:
        type: string
      textStringForTagging:
        type: string
      normalizedForm:
        type: string
      normalizedFormGroup:
        type: integer
  Error:
    required:
      - code
      - error_code
      - message
    properties:
      code:
        type: integer
        format: int32
        description: HTTP status code
      error_code:
        type: string
        description: Error category
      message:
        type: string
        description: Error message shown in api response
