UPDATE client set state='DISABLED' where name not in ('247ai',     
'Dish',
'First American (Home Warranty)',
'firstam'
'Delta',
'Botstore',
'Amex US',
'Assurant',
'247inc',
'247ai',
'247ai Referencebot',
'247ai Aisha',
'ModelingWorkbench',
'British Gas',
'SiriusXM',
'CapitalOne',
'airtel',
'Choice Hotels',
'Columbia',
'Columbia General',
'Columbia Sorel',
'Columbia Mountainhw',
'test-default',
'CSSP',
'Marriott',
'Farmers',
'Hilton',
'Tellme',
'Mitsui',
'optus',
'eversource',
'searsonline',
'client_retail',
'client_Telco',
'UPS',
'Ebay',
'Ebay UK',
'Ebay DE',
'cap1caat');