package com.tfs.learningsystems.db;


import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.sql.Timestamp;

@Data
@EqualsAndHashCode(callSuper = false)
@Entity
@Table(name = "metrics")
public class MetricsBO extends BusinessObject<MetricsBO, String> {
    public static final String DB_PREFIX = "met";

    @Id
    @GeneratedValue
    @Column(name = "id")
    @ApiModelProperty(readOnly = true, value = "internal id generated by MWB", example = "12")
    protected Integer id;

    @Column(name = "client_id")
    @ApiModelProperty(required = true, value = "client id to which this metric belongs to", example = "159")
    protected Integer clientId;

    @Column(name = "node_name")
    @ApiModelProperty(value = "node_name", example = "node1")
    protected String nodeName;

    @Column(name = "model_name")
    @ApiModelProperty(value = "model_name", example = "model1")
    protected String modelName;

    @Column(name = "metric_date")
    @ApiModelProperty(value = "metric date", example = "2021-05-12 21:22:23")
    protected Timestamp metricDate;

    @Column(name = "volume")
    @ApiModelProperty(value = "volume count", example = "100")
    protected Integer volume;

    @Column(name = "escalation")
    @ApiModelProperty(value = "escalation count", example = "60")
    protected Integer escalation;

    @Column(name = "created_at")
    @ApiModelProperty(value = "created time", example = "1343805819061")
    protected Long createdAt;

    @Column(name = "modified_at")
    @ApiModelProperty(readOnly = true, value = "Last modified date", example = "1343805819062")
    protected Long modifiedAt;

    @Column(name = "version")
    @ApiModelProperty(required = true, value = "version value", example = "8")
    protected Integer version;

    @Override
    public String getDbPrefix() {
        return DB_PREFIX;
    }
}
